### ISSUE TITLE
#resource.dialect# not getting replaced

### ISSUE THREAD

**Issue by shankarasta** [Acosix/alfresco-audit#5]
Hi Alex,

I am trying to deploy your audit tool onto an alfresco version 7.0.1 deploy.
I am using PostgreSQL as my database.
I have deployed alfresco using their ansible playbook as a local install.
I apply your amp and start my application and I get the following exception:
Caused by: org.springframework.core.NestedIOException: Failed to parse config resource: class path resource [alfresco/module/acosix-audit/ibatis/sqlmap-config.xml]; nested exception is org.apache.ibatis.builder.BuilderException: Error parsing SQL Mapper Configuration. Cause: org.apache.ibatis.builder.BuilderException: Failed to get resource: alfresco/module/acosix-audit/ibatis/#resource.dialect#/propertyTablesCleanup-SqlMap.xml
        at org.alfresco.ibatis.HierarchicalSqlSessionFactoryBean.buildSqlSessionFactory(HierarchicalSqlSessionFactoryBean.java:487)
        at org.alfresco.ibatis.HierarchicalSqlSessionFactoryBean.afterPropertiesSet(HierarchicalSqlSessionFactoryBean.java:384)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1847)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1784)
        ... 54 more
Caused by: org.apache.ibatis.builder.BuilderException: Error parsing SQL Mapper Configuration. Cause: org.apache.ibatis.builder.BuilderException: Failed to get resource: alfresco/module/acosix-audit/ibatis/#resource.dialect#/propertyTablesCleanup-SqlMap.xml
        at org.alfresco.ibatis.HierarchicalXMLConfigBuilder.parseConfiguration(HierarchicalXMLConfigBuilder.java:140)
        at org.alfresco.ibatis.HierarchicalXMLConfigBuilder.parse(HierarchicalXMLConfigBuilder.java:120)
        at org.alfresco.ibatis.HierarchicalSqlSessionFactoryBean.buildSqlSessionFactory(HierarchicalSqlSessionFactoryBean.java:481)
        ... 57 more
Caused by: org.apache.ibatis.builder.BuilderException: Failed to get resource: alfresco/module/acosix-audit/ibatis/#resource.dialect#/propertyTablesCleanup-SqlMap.xml
        at org.alfresco.ibatis.HierarchicalXMLConfigBuilder.mapperElement(HierarchicalXMLConfigBuilder.java:368)
        at org.alfresco.ibatis.HierarchicalXMLConfigBuilder.parseConfiguration(HierarchicalXMLConfigBuilder.java:138)
        ... 59 more

Clearly #resource.dialect# is not being replaced.
Is there any magic to getting this to work?

Also, the pom.xml file is pointing to 
<parent>
        <groupId>de.acosix.alfresco.maven</groupId>
        <artifactId>de.acosix.alfresco.maven.project.parent-5.0.d</artifactId>
        <version>1.3.1-SNAPSHOT</version>
    </parent>

But it looks like 1.3.1-SNAPSHOT is missing from the repo. Needless to say, changing it to 1.3.1 works.

**Comment by shankarasta** [comment]
Hi Alex,

Thanks for you help on this. By refactoring two folders:
1. org.hibernate.dialect.Dialect
2. org.hibernate.dialect.MySQLInnoDBDialect

to 
org.alfresco.repo.domain.dialect.Dialect
org.alfresco.repo.domain.dialect.MySQLInnoDBDialect

I was able to get rid of the #resource.dialect# error.

But, I had to make one more change to the job-context.xml file in order for all the job trigger beans to be instantiated.
Wherever I found **_\${${moduleId}._************
I had to "hard_code" the module name for it to work.
I had to change it to ${audit-repo.****** }.

As an example, I changed
value="\${${moduleId}.job.consolidateActiveUsersAudit.cron}

to

value="${audit-repo.job.consolidateActiveUsersAudit.cron}"

Tomcat/spring did not like value="\${audit-repo.job.consolidateActiveUsersAudit.cron}".

maven on compilation was not removing "\".

Could this be a maven compiler version issue?

Thanks again for all your help,
Shankar

**Comment by AFaust** [comment]
The `\` is configured as an escape character and should be removed after Maven is done, so it should not show up in the Spring XML files afterwards. I typically have my parent POM set to force specific versions of Maven plugins to avoid exactly those cases of different versions of Maven (plugins) resulting in different output. But maybe some potential mismatch slipped by....
